[theme]
primaryColor = "#4A90E2"  # Bright blue from the graph
backgroundColor = "#1E2126"  # Dark background
secondaryBackgroundColor = "#262B32"  # Slightly lighter dark for cards/sections
textColor = "#FFFFFF"  # White text
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 